# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Comets' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Comets
pod 'EstimoteSDK', '~> 3.7.0'
end

target 'PixelPusherTests' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PixelPusherTests

end
